kind: pipeline
type: docker
name: susy-web


pipeline:
  publish:
    image: plugins/docker
    dockerfile: ./Dockerfile
    context: .
    repo: susyone/susy-web
    tags: ["latest", "master", "main"]
    secrets: [docker_username,docker_password]

  deployment:
    image: appleboy/drone-ssh
    host: susy.one
    key:
      from_secret: password
    username:
      from_secret: ssh_username
    port:
      from_secret: ssh_port
    script:
        - cd /var/www/fresh-susy-web && bash rebuild.sh
    when:
      branch:
        - master

trigger:
  branch:
  - master
  - feature/ci